### ISSUE TITLE
Request to move Compuware Topaz for Enterprise Data Jenkins plugin repository to jenkinsci

### ISSUE THREAD

**Issue by ratishkr** [jenkins-infra/repository-permissions-updater#2347]
### Repository URL

https://github.com/ratishkr/compuware-topaz-for-enterprise-data-plugin

### New Repository Name

compuware-topaz-for-enterprise-data-plugin

### Description

Compuware's Topaz for Enterprise Data is a data management product with automation to speed data extraction, privatization and loading. The plugin allows Jenkins users to run ted specifications.

### GitHub users to have commit permission

@bszydlowski
@ratishkr
@cpwr-github

### Jenkins project users to have release permission

cpwr_jenkins

### Issue tracker

GitHub issues

**Comment by daniel-beck** [comment]
Needs security review, at a glance there are already a few problems.

**Comment by timja** [comment]
fyi @Wadeck

**Comment by Wadeck** [comment]
Tracked internally as JENSEC-1757, thanks for the ping!

**Comment by markbsigler** [comment]
@Wadeck and @daniel-beck 

Can you help out a former Bee and let @ratishkr know what we need to do to move this one along?

**Comment by Wadeck** [comment]
@markbsigler @ratishkr The audit is currently in review, we have not forgotten you.

**Comment by vzamoragbmc** [comment]
Any updates on this @Wadeck?

Thanks

**Comment by timja** [comment]
just remove them from the list in the description

**Comment by Wadeck** [comment]
> Hi, is there a way to remove @bszydlowski and @ratishkr from the developers?

Interesting case as the plugin repository is hosted by @ratishkr 

@vzamoragbmc we had reported 4 vulnerabilities to cpwr.jenkins@compuware.com (email used to back `cpwr_jenkins` in Jira) on Feb 17, but there was no commits on master branch of https://github.com/ratishkr/compuware-topaz-for-enterprise-data-plugin since that.

So from my PoV, the security audit results were not tackled yet. Now due to the change of maintainers, perhaps you lost part of the information.

As you are owning the mentioned email, I would suggest you to look for an email called `[Hosting#2347] Compuware Topaz for Enterprise Data Jenkins plugin` to see what is missing there.

**Comment by vzamoragbmc** [comment]
Thank you @Wadeck, I do not have access to those emails, but I will request it.

In this case what do you suggest? As you say @ratishkr  is hosting the plugin but he doesn't work with us anymore and we don't have access to his github. Should I create a fork and fix the issues?

Also I can't edit the description for some reason @timja.

Thanks to both.

**Comment by timja** [comment]
Probably best to create a new request then with you having ownership of it. and yes just fork it and use that as the new source

**Comment by vzamoragbmc** [comment]
Thanks Tim, can we close this then?

Yeah, sorry I didn't mention that...
