### ISSUE TITLE
Jenkins Casdoor Authentication Plugin

### ISSUE THREAD

**Issue by Abingcbc** [jenkins-infra/repository-permissions-updater#2379]
### Repository URL

https://github.com/casdoor/jenkins-casdoor-auth

### New Repository Name

casdoor-auth-plugin

### Description

Casdoor provides a plugin for users to login Jenkins. We want to release this plugin into Jenkins plugin market.

### GitHub users to have commit permission

hsluoyz
abingcbc

### Jenkins project users to have release permission

hsluoyz
abingcbc

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by timja** [comment]
on hold till @Wadeck responds

**Comment by Wadeck** [comment]
Quick look at the code, we will need a more deeper audit, found in [CasdoorSecurityRealm.java#L57](https://github.com/casdoor/jenkins-casdoor-auth/blob/2f55bef45787dbfab6d68d4886272ea5b4338ec0/src/main/java/org/casbin/casdoor/CasdoorSecurityRealm.java#L57) the secret does not seem stored encrypted. Also, the session is not invalidated after login.
Tracked internally as JENSEC-1763 where we will confirm the stuff and find others potentially.

**Comment by Abingcbc** [comment]
@Wadeck Thanks for your reply. We have fixed the problems in this PR: https://github.com/casdoor/jenkins-casdoor-auth/pull/7
1. We use `Secret` of `hudson` to store client secrets instead of plain string.
2. The session will be invalidated when users log out by `doLogout`.

BTW, can we access JENSEC-1763 to follow up?

**Comment by Wadeck** [comment]
@Abingcbc  The audit is still pending.

FYI when I mentionned "the session is not invalidated after login" it was not a mistake. It's really after a **login**, you have to invalidate the session to prevent session hijacking.

JENSEC-1763 is an internal ticket.

**Comment by hsluoyz** [comment]
Hi @Wadeck 

> FYI when I mentionned "the session is not invalidated after login" it was not a mistake. It's really after a login, you have to invalidate the session to prevent session hijacking.

OK. We thought it was "logout". For "login", it is actually a feature called `enableSigninSession` (see: https://door.casdoor.com/applications/app-built-in ). It's a boolean value. When it's true, Casdoor will preserve the session after login. It will be usable for the Single-Sign-On scenario: a user logs into app A and Casdoor preserves the session. So when the user tries to log into app B, app B can do a silent login to Casdoor and Casdoor will remember the same user and complete the OAuth login silently without user interaction.

![image](https://user-images.githubusercontent.com/3787410/155748476-c5441529-db42-4d97-8c79-a594163bb185.png)

Like other OAuth IdP, Casdoor uses redirect URL whitelist to control who can connect to Casdoor as an application, so I think there will be very limited space for session hijacking because the attacker doesn't control the allowed domains. To be more secure, we have turned off this feature by default: https://github.com/casdoor/casdoor/commit/c58a6d87253ffb16aecb977002923c76bc1fe192

**Comment by Wadeck** [comment]
@hsluoyz Your explanation makes total sense, from Casdoor PoV. Allowing a single user to connect multiple applications without having to reconnect everytime, like most of the SSO. 
The problem I highlighted is from Jenkins PoV. If someone is able to force the Jenkins session of a user, that attacker will be able to force the session of the victime in Jenkins context, and thus getting access.
My recommendation is to simply invalidate the session after the doFinish part of the OAuth process. Example of such invalidation in the [GitHub OAuth plugin](https://github.com/jenkinsci/github-oauth-plugin/blob/00535e57c06bc98fa91d6d08eec5d672444748d0/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java#L405-L410).

The two sessions are "related" but not under the same responsability and not serving the same purpose.

FTR: https://door.casdoor.com/applications/app-built-in is unreachable.

PS: to be explicit, my superficial audit was superficial, a more complete one is coming soon, with other points to cover.

**Comment by Abingcbc** [comment]
@Wadeck Casdoor demo is avaible now at https://door.casdoor.com/applications/app-built-in . The username is `admin` and the password is `123`.

**Comment by Kevin-CB** [comment]
Hello @Abingcbc ,

We were able to perform a more complete audit on your plugin, here are the feedback:

- As said before, it seems that you don't invalidate your session when you login.
As mentioned by Wadeck, https://door.casdoor.com/applications/app-built-in is unreachable, we can't test your feature.
We would recommand you to simply invalidate the session after the doFinish part of the OAuth process.

- You are using dependencies with a known vulnerabilities through:
  - casdoor-auth > com.google.oauth-client:google-oauth-client => https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7692
  - casdoor-auth > org.casbin:casdoor-java-sdk > com.fasterxml.jackson.core:jackson-databind => https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
  - casdoor-auth > com.google.oauth-client:google-oauth-client > com.google.http-client:google-http-client > org.apache.httpcomponents:httpclient => https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13956
  - casdoor-auth > com.google.oauth-client:google-oauth-client > com.google.http-client:google-http-client > org.apache.httpcomponents:httpclient => https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-1498
  - casdoor-auth > com.google.oauth-client:google-oauth-client > com.google.http-client:google-http-client > org.apache.httpcomponents:httpclient => https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3577
  - casdoor-auth > com.google.oauth-client:google-oauth-client > com.google.http-client:google-http-client > org.apache.httpcomponents:httpclient => https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-31517
  - casdoor-auth > com.google.oauth-client:google-oauth-client > com.google.http-client:google-http-client > org.apache.httpcomponents:httpclient => https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-6153
  - casdoor-auth > org.casbin:casdoor-java-sdk > com.squareup.okhttp3:okhttp > org.jetbrains.kotlin:kotlin-stdlib => https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-29582

- A kind of open redirect vulnerability, in the method [doCommenceLogin](https://github.com/casdoor/jenkins-casdoor-auth/blob/ad59f0b3ff70b5df0a45c9cbf2d7c93635a073e1/src/main/java/org/casbin/casdoor/CasdoorSecurityRealm.java#L81), you do not restrict the `Referer` to Jenkins, which could in some cases be used to perform phising attack.

- We also want to inform you to be careful in the future, with the [web methods present in the securityRealm](https://github.com/casdoor/jenkins-casdoor-auth/blob/ad59f0b3ff70b5df0a45c9cbf2d7c93635a073e1/src/main/java/org/casbin/casdoor/CasdoorSecurityRealm.java#L260-L286) as they're accesible to all users. For the moment they are trivial and do not represent a threat but if you add features please protect them.
https://www.jenkins.io/doc/developer/security/form-validation/#securely-implementing-form-validation

I will let you correct the different findings and ping us when you are done or if you have questions.

**Comment by Abingcbc** [comment]
@NotMyFault Yes, we still want to release this plugin. There are some minor bugs we forgot. We will fix them as soon as possible and then provide a list of our fixes for these security findings.
THX :)

**Comment by Abingcbc** [comment]
@NotMyFault Here are our fixes for the security findings:

1. Invalidating session: There is an option in Casdoor. User can configure whether keeping session after they login.
<img width="193" alt="image" src="https://user-images.githubusercontent.com/34068205/195351319-e52ab83e-a9ff-418b-8032-5bb735c2b857.png">

2. Vulnerable dependencies: https://github.com/casdoor/casdoor-java-sdk/pull/20
3. Random state: https://github.com/casdoor/casdoor/issues/564
4. Restrict Referer: We think that this dangerous situation is very rare, but it greatly limits the scenarios in which Casdoor can be used. Furthermore, other OAuth Jenkins Plugin, such as KeyCloak, doesn't launch such restriction too. https://github.com/jenkinsci/keycloak-plugin/blob/de8970c963aa47d30313cf42c83d6cb5cc0d6334/src/main/java/org/jenkinsci/plugins/KeycloakSecurityRealm.java#L170

**Comment by Kevin-CB** [comment]
Hello @Abingcbc,

It seems the issue with the state parameter isn't solved, indeed on the plugin you just deleted it.

What you need to do is to send a random value when starting an authentication request and validate the received value when processing the response. (https://auth0.com/docs/secure/attack-protection/state-parameters#csrf-attacks)

Otherwise, concerning the referrer, we agree to not consider this case as a vulnerability.

If something is not clear, do not hesitate to tell us, we will try to help you.

**Comment by Abingcbc** [comment]
Hi, @Kevin-CB, we have fixed the random state in the following PRs:
https://github.com/casdoor/jenkins-casdoor-auth/pull/9
https://github.com/casdoor/casdoor-java-sdk/pull/39
If we misunderstood the problem, please point it out. THX :)

**Comment by Kevin-CB** [comment]
Hi @Abingcbc,

I totally agree with what Wadeck said, [casdoor/CasdoorSecurityRealm.java#L93](https://github.com/Abingcbc/jenkins-casdoor-auth/blob/32fddc06c9f9c5a578c4308be2a5e79d4ec47f96/src/main/java/org/casbin/casdoor/CasdoorSecurityRealm.java#L93) should use [MessageDigest#isEqual()](https://docs.oracle.com/javase/7/docs/api/java/security/MessageDigest.html#isEqual(byte%5B%5D,%20byte%5B%5D)).

Otherwise on the plugin side everything looks good to me, but I am still very curious about your change in your SDK.
Are you retrieving the state from the `doCommenceLogin` and sending it back? 
From what I read at [service/CasdoorAuthService.java#L109](https://github.com/Abingcbc/casdoor-java-sdk/blob/1be10d1ef6b995991555fd2ee38f5a759c574964/src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java#L109), you're sending a state equals to ApplicationName.

**Comment by Abingcbc** [comment]
Hi @Kevin-CB . There are two versions of `getSigninUrl`. 
https://github.com/Abingcbc/casdoor-java-sdk/blob/1be10d1ef6b995991555fd2ee38f5a759c574964/src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java#L108
https://github.com/Abingcbc/casdoor-java-sdk/blob/1be10d1ef6b995991555fd2ee38f5a759c574964/src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java#L112

The one which sending ApplicatioName is just to prevent breaking change for users who use previous version of SDK. In the plugin, we use the second version and send a random state to Casdoor.

**Comment by Abingcbc** [comment]
@Wadeck @Kevin-CB We have fixed the way to compare the state in https://github.com/casdoor/jenkins-casdoor-auth/pull/10. PTAL :)

**Comment by Kevin-CB** [comment]
I reviewed your last changes, and everything seems good from a security aspect.

You can continue the hosting process.

**Comment by Abingcbc** [comment]
@NotMyFault Fixed with https://github.com/casdoor/jenkins-casdoor-auth/pull/11 PTAL :)
