### ISSUE TITLE
Grype vulnerability scanner

### ISSUE THREAD

**Issue by dtbaum** [jenkins-infra/repository-permissions-updater#2396]
### Repository URL

https://github.com/dtbaum/grypescanner-plugin

### New Repository Name

grypescanner-plugin

### Description

[Grype](https://github.com/anchore/grype) is a vulnerability scanner for container images and filesystems. This grypescanner-plugin scans a given target and saves a report as job artifact. 
There is no such grype plugin yet.

### GitHub users to have commit permission

@dtbaum 

### Jenkins project users to have release permission

tbaum

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by Wadeck** [comment]
Superficial audit:
- [GrypeScannerStep.java#L57](https://github.com/dtbaum/grypescanner-plugin/blob/7ef28f66e97e00ee4e7cb1c570ea077d10c7c747/src/main/java/io/jenkins/plugins/grypescanner/GrypeScannerStep.java#L57) and [GrypeScanner.java#L21](https://github.com/dtbaum/grypescanner-plugin/blob/7ef28f66e97e00ee4e7cb1c570ea077d10c7c747/src/main/java/io/jenkins/plugins/grypescanner/GrypeScanner.java#L21) I am not a big fan of such approach. It means, that once you install this plugin, anyone with write access to https://github.com/anchore/grype will be able to execute code in the build. I imagine that since you install this plugin, we can assume that the admin is trusting the grype project in general and thus this is ok.
- 💡 [GrypeScannerStep.java#L142](https://github.com/dtbaum/grypescanner-plugin/blob/7ef28f66e97e00ee4e7cb1c570ea077d10c7c747/src/main/java/io/jenkins/plugins/grypescanner/GrypeScannerStep.java#L142) seems not what you expect. This method is checking if the build step fits the project type, not the agent where it will be executed on. If you have a Windows controller and a Unix agent, it will wrongly return false. If you have a Unix controller with Windows agent, it will wrongly return true.

So fine to move forward :-)

**Comment by dtbaum** [comment]
Thanks, I have addressed both points. 
I added an 'autoInstall' checkbox in the UI - the user can choose to use his 'grype' from the PATH or download and install it each time. In my own use case the second variant is an appropriate one, the explanation would be too long :-)
I added some more improvements, looking forward to the feedback!

**Comment by Wadeck** [comment]
@dtbaum Thank you very much for the changes. Having the install + existing location is perfectly fine 👍 
Also great job on the system detection 👍 

@timja Audit complete with success :)

**Comment by timja** [comment]
Non blocking comments:

1. Jelly files are formatted all over the place, would be good to run a formatter over them
2. Java files do not follow Java formatting standard, we're starting to adopt the spotless-maven-plugin with google format in a few places, something to consider.
3. Markdown broken in https://github.com/dtbaum/grypescanner-plugin#usage-in-a-pipeline, ensure you wrap code blocks in triple backticks to make it render better
4. There's TODO's in the issue tracker and contributing section of the README
