### ISSUE TITLE
agent maintenance plugin

### ISSUE THREAD

**Issue by mawinter69** [jenkins-infra/repository-permissions-updater#2431]
### Repository URL

https://github.com/SAP/agent-maintenance-plugin

### New Repository Name

agent-maintenance-plugin

### Description

This plugin allows to define maintenance windows for agents. During a maintenance window no new builds will start, running builds have the possibility to finish if desired (this can be limited so that builds are aborted if they take too long).
This is very helpful when you have many permanent agents that and you have to take them offline due to maintenance activities like OS updates, hardware issues or other things. Those things tend to be done outside usual office hours on the weekend or in the night. 
So far Jenkins core only offers the possibility for agents to be taken offline on a schedule, on demand or always. I haven't found any other plugin that provides the desired functionality.

### GitHub users to have commit permission

mawinter69

### Jenkins project users to have release permission

mawinter69

### Issue tracker

Jira

**Comment by daniel-beck** [comment]
```
org.apache.maven.plugin.MojoFailureException: The POM violates the code style. Please format it by running `mvn tidy:pom`.

**Comment by mawinter69** [comment]
fixed the errors in the pom and also some compile errors (deprecated javax annotations)

**Comment by mawinter69** [comment]
Any news here?

**Comment by timja** [comment]
@Wadeck did you want to check this?

**Comment by Wadeck** [comment]
**Superficial security audit:**
- XSS in https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/resources/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink/index.jelly#L73-L82.

<details>

<summary>XSS details</summary>

As a user with Computer/Configure, if I modify the information sent to the constructor of MaintenanceWindow, I have the possibility to force the ID. Could be easily done by modifying the HTML as done in the example, or directly modifying the request sent. Also, this could be done by modifying the hidden id field when editing such item.

Then the ID is injected into the onClick javascript, leading to a stored XSS.

Also, same location, the displayName of a computer is not something you should trust like this.

### Configure

![Screenshot_2022-03-17_184347_001](https://user-images.githubusercontent.com/2662497/158863497-e4e76603-e599-45d9-9b65-0b4440b010ea.png)


### Trigger

![Screenshot_2022-03-17_184440_001](https://user-images.githubusercontent.com/2662497/158863511-c22c70b3-19a0-4ab1-bf85-59d7b53c2408.png)


**Recommendation:** https://www.jenkins.io/doc/developer/security/xss-prevention/#passing-values-to-javascript

</details>

----

**Bug:**
- When I try to edit an existing maintenanceWindow, I am getting JS error


<details>

<summary>JS error</summary>

Done without the XSS payload, just regular characters inside.

![Screenshot_2022-03-17_184830_001](https://user-images.githubusercontent.com/2662497/158864258-4b22e1fc-157a-4f92-b90f-7ce686a226f2.png)

</details>

----

**Misc:** 
- https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/resources/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceAction/config.jelly#L31 This code seems to work, but I imagine more because browsers are very tolerant, there is a missing `]` at the end.

**Comment by mawinter69** [comment]
fixed the XSS by urlencoding the id. I hope that this is sufficient.
The displayName of a computer is used in a localized expression which according to the documentation should be escaped.

**Comment by Wadeck** [comment]
Thanks for the quick reaction, we will proceed with a deeper audit, internally tracked as JENSEC-1793.

**Comment by Kevin-CB** [comment]
Hi @mawinter69, 

We were able to perform a more complete audit on your plugin, here are the feedback:


Stored XSS with c.displayName:

- A tooltip does not provide an escape by default, in [MaintenanceLink/index.jelly#L82](https://github.com/SAP/agent-maintenance-plugin/blob/4f48731a4ea77ca76d30e7ae90d8388cb9dfa205/src/main/resources/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink/index.jelly#L82), you're passing `c.displayName` in a tooltip.
`c.displayName`, if not defined, it corresponds to the name of the agent, but some plugins offer to define it which will then be used without escapes, allowing a stored XSS.

- In [MaintenanceLink/index.jelly#L74](https://github.com/SAP/agent-maintenance-plugin/blob/4f48731a4ea77ca76d30e7ae90d8388cb9dfa205/src/main/resources/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink/index.jelly#L74), you're using `c.displayName` in a localized expression within JS. Localized expression are effective for HTML, in JS they're not sufficient. It's then possible to perform a stored XSS by calling your agent `'+alert(1)+'` (that does not contain forbidden characters for an agent name).

Recommendation:
https://www.jenkins.io/doc/developer/security/xss-prevention/#passing-values-to-javascript

---
Potential unprotected actions:

In order to prevent any potentiel unprotected actions or web methods from your [agent-maintenances page](https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/java/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink.java#L39), we highly recommend you to restrict who can access it.

Recommendation:
https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/java/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink.java#L39

We will let you correct the finding and ping us when you are done or if you have questions.

**Comment by timja** [comment]
> In order to prevent any potentiel unprotected actions or web methods from your [agent-maintenances page](https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/java/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink.java#L39), we highly recommend you to restrict who can access it.

It seems to be correctly permission checked?
https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/java/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink.java#L194

and elsewhere.

and the page itself seems to correctly hide the buttons if you don't have access to modify.
https://github.com/SAP/agent-maintenance-plugin/blob/bda34bc808dd79c163fe8154191fd4b5fb16f9c6/src/main/resources/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceAction/index.jelly#L78

So likely not an issue, but worth checking

**Comment by Kevin-CB** [comment]
Indeed, the methods and actions are protected.
This is only a recommendation to guarantee security and avoid an improper implementation in the future.

**Comment by mawinter69** [comment]
I created 2 agents with names "+alert(123)+" and '+alert(123)+' (only works on Unix). In the tooltip this is not an issue it seems. The double quotes are properly escaped, the single quotes are not a problem as they are inside a double quoted string.
If jelly would auto escape single quotes it would be so easy. 

Regarding the permissions, that should hopefully work as expected. This only applies for the MaintenanceLink when the system_read permissions are enabled. If not you have to be admin anyway to access it.
As system_read doesn't imply any computer permissions, the maintenance windows need to be checked for each agent if they can be deleted.

**Comment by Kevin-CB** [comment]
Excuse me, for the [MaintenanceLink/index.jelly#L74](https://github.com/SAP/agent-maintenance-plugin/blob/4f48731a4ea77ca76d30e7ae90d8388cb9dfa205/src/main/resources/com/sap/prd/jenkins/plugins/agent_maintenance/MaintenanceLink/index.jelly#L74) you're right, single quotes are not a problem I just got confused writing the payload, you've to use double quote `"+alert(1)+"` (and indeed this only works on Unix since Windows doesn't support files with `"`).
![image](https://user-images.githubusercontent.com/91883215/159345055-0cab9013-0ec5-4b22-bdb0-41281d0b8c98.png)

In the tooltip, this is a problem, you just need to use a different payload: `<img/src/onerror=alert(1)` ( `<`, `>` and `/` are not allowed for an agent name, but since you're using displayName, some plugins offer to override the `getDisplayName` defined by `Computer`, which will allow these characters).
![image](https://user-images.githubusercontent.com/91883215/159344877-24631f1a-07ff-405c-b770-9503d844796e.png)

Concerning the permissions, there is no security issues, we simply advise you to implement the following recommendations in order to follow the best pratices and to guarantee optimal security in future implementations.
https://www.jenkins.io/doc/developer/extensibility/action-for-all-projects/#restrict-access

**Comment by mawinter69** [comment]
should be fixed now

**Comment by timja** [comment]
@Kevin-CB Permission wise this appears to be implemented best practice wise.

System read is to allow users to be able to read and not modify.
It seems very intentional here so that users can see the schedule.

----

@mawinter69 you appear to be using the old style table desgin.

If you want to switch to the new design you would need to use the latest LTS as the minimum 2.332.1

Here's a screenshot of the docs from: https://github.com/jenkinsci/ui-samples-plugin/pull/14
![image](https://user-images.githubusercontent.com/21194782/159434289-7185d5fb-8448-4b59-bcec-5a6f86984c3a.png)

**Comment by Kevin-CB** [comment]
I reviewed your fix and everything looks good in terms of security.
