### ISSUE TITLE
AGC App Upload

### ISSUE THREAD

**Issue by josholadele** [jenkins-infra/repository-permissions-updater#2444]
### Repository URL

https://github.com/AppGalleryConnect/agc-jenkins-plugin

### New Repository Name

agc-app-upload-plugin

### Description

Introduction
Jenkins Plugin to support uploading your Android Application to AppGallery

This makes use of the [AppGallery Connect API](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-overview-0000001158245083)[](https://github.com/AppGalleryConnect/agc-jenkins-plugin#resources) to upload your build android application to AppGallery.

Note that you will need to have already build the APK or AAB file before using this plugin

Resources
[AppGallery Connect](https://developer.huawei.com/consumer/en/agconnect/)[](https://github.com/AppGalleryConnect/agc-jenkins-plugin#how-to-contribute) - Learn more about AppGallery Connect Services, and signup for a developer account!

How to Contribute
We welcome reporting of issues!

### GitHub users to have commit permission

@josholadele

### Jenkins project users to have release permission

josholadele

### Issue tracker

GitHub issues

**Comment by timja** [comment]
`secret` should be of type `Secret`

@Wadeck anything else you want to check, it's just one class:
https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/main/src/main/java/com/huawei/jenkins/AppGalleryUploadBuilder.java#L31

**Comment by Wadeck** [comment]
@timja You catch it :) also the `f:password` should be used for https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/a85adf894e006f1647f2d645a9c3296c152ea6af/src/main/resources/com/huawei/jenkins/AppGalleryUploadBuilder/config.jelly#L7

But due to https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/a85adf894e006f1647f2d645a9c3296c152ea6af/src/main/java/com/huawei/jenkins/AppGalleryUploadBuilder.java#L186, I will need to do a deeper audit, it seems that we can steal any file in the controller.

**Comment by josholadele** [comment]
Hi there
Please has there been any updates on this?

**Comment by Kevin-CB** [comment]
Hi @josholadele, 

We were able to perform a more complete audit on your plugin, here are the feedback:

You're using a regular `File` type in [jenkins/AppGalleryUploadBuilder.java#L188-L190](https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/84147f1710c7daeed354de2426f977e44650b7c8/src/main/java/com/huawei/jenkins/AppGalleryUploadBuilder.java#L188-L190), allowing an arbitrary file upload on the controller. To avoid browsing on the controller, we'll recommend you to pass `FilePath workspace` to the `#perform` method and to use a method similar to `workspace.child(getPath())` to retrieve the file on the agent.

We will let you correct the finding and ping us when you are done or if you have questions.

**Comment by josholadele** [comment]
Updated @daniel-beck

**Comment by daniel-beck** [comment]
The field needs to be `transient`, otherwise an attempt will be made to serialize the `FilePath` when the job is saved (through a code path other than submitting the config form).

[This getter](https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/da1d422123975a942d691ba125e6fcfb6f03a9cb/src/main/java/com/huawei/jenkins/AppGalleryUploadBuilder.java#L44) should return `Secret`, otherwise the secret will be regenerated constantly on submission of unmodified configuration.

**Comment by josholadele** [comment]
Done @daniel-beck

**Comment by josholadele** [comment]
Hello there
Please has there been any updates on this?

**Comment by Kevin-CB** [comment]
I've reviewed your corrections and we're good in terms of security, the hosting process can continue 🙂

**Comment by josholadele** [comment]
Alright, thanks

**Comment by josholadele** [comment]
"Once all requirements have been satisfied, your repository will be forked into the jenkinsci organization and you will be invited to join it."

**Comment by josholadele** [comment]
Am I waiting on this now? Or how do I go about it?

**Comment by timja** [comment]
Don't forget to update this: https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/main/src/main/resources/index.jelly#L3

**Comment by josholadele** [comment]
@timja

**Comment by josholadele** [comment]
> Don't forget to update this: https://github.com/AppGalleryConnect/agc-jenkins-plugin/blob/main/src/main/resources/index.jelly#L3

Alright, will get to it
