### ISSUE TITLE
Hosting Request for MergeBase SCA plugin

### ISSUE THREAD

**Issue by delanAtMergebase** [jenkins-infra/repository-permissions-updater#2465]
### Repository URL

https://github.com/mergebase/mergebase-sca

### New Repository Name

mergebase-sca-plugin

### Description

The MergeBase SCA plugin allows MergeBase users who are also Jenkins users to run the MergeBase tool with an automated build step. 

The plugin runs the MergeBase tool and prints a report, as well as sends the report back to the MergeBase dashboard.

### GitHub users to have commit permission

@delanAtMergebase
@juliusmusseau

### Jenkins project users to have release permission

delanAtMergebase
juliusmusseau

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck 

From a quick look over likely `customToken` should by of type `Secret`

and using `f:password` for UI: https://github.com/mergebase/mergebase-sca/blob/master/src/main/resources/com/mergebase/jenkins/MergebaseStepBuilder/config.jelly#L13

**Comment by Wadeck** [comment]
Yes your finding is good.

Also, I have some doubts about https://github.com/mergebase/mergebase-sca/blob/7a044e3708991feb294199a399ba2d0634c4d2fa/src/main/java/com/mergebase/jenkins/MergeBaseRun.java#L34 as the path seems to be configured at the step level, it allow attackers with Job/Configure to download tooling to the controller. Gut feeling: this should be a global config, not a per-job config.

I will file an internal ticket to cover it completely => JENSEC-1800. 
ℹ️ ETA perhaps a bit longer than usual as we have several other tasks in parallel.

**Comment by delanAtMergebase** [comment]
I will address these issues before you do your full review. Thanks for the initial findings!

**Comment by Kevin-CB** [comment]
Hi @delanAtMergebase.

We're able to perform a more complete audit on your plugin here are the feedback:

 - Your `customerToken` need to be encrypted to not get serialized to disk as plain text, for that you need to declare it as a `Secret`. ([pipeline/MergebasePipelineStep.java#L33](https://github.com/mergebase/mergebase-sca/blob/427fb96d15aace84af3012b3768761cd71c2170b/src/main/java/com/mergebase/jenkins/pipeline/MergebasePipelineStep.java#L33) & [jenkins/MergebaseStepBuilder.java#L33](https://github.com/mergebase/mergebase-sca/blob/427fb96d15aace84af3012b3768761cd71c2170b/src/main/java/com/mergebase/jenkins/MergebaseStepBuilder.java#L33))
 Also you'll need to use `f:password` for UI in [MergebaseStepBuilder/config.jelly#L14](https://github.com/mergebase/mergebase-sca/blob/427fb96d15aace84af3012b3768761cd71c2170b/src/main/resources/com/mergebase/jenkins/MergebaseStepBuilder/config.jelly#L14).

Moreover in [jenkins/MergebaseConfig.java#L7](https://github.com/mergebase/mergebase-sca/blob/427fb96d15aace84af3012b3768761cd71c2170b/src/main/java/com/mergebase/jenkins/MergebaseConfig.java#L7) you're implementing a `Serializable` interface while it's not needed, this should be removed. (If you want to keep it you should transform `customerToken` into a `Secret` type)

Recommendation:
https://www.jenkins.io/doc/developer/security/secrets/

--- 

- An arbitrary folder write vulnerability due to [jenkins/MergeBaseRun.java#L37](https://github.com/mergebase/mergebase-sca/blob/7a044e3708991feb294199a399ba2d0634c4d2fa/src/main/java/com/mergebase/jenkins/MergeBaseRun.java#L37)
 You're downloading a tool to the controller and the path can be specified by a user to create folder anywhere on the controller (e.g: : `../../newFolder`).
 
Recommendation: 
You should move this configuration to a global level (by admin only) or restrict it to workspace (forbidding non-relative paths).

We will let you correct the finding and ping us when you are done or if you have questions.

**Comment by Kevin-CB** [comment]
Hi @delanAtMergebase, 

I was able to review and test your latest version and everything seems ok on security point of view! 

We can continue the hosting process.

**Comment by timja** [comment]
I would suggest updating this file:
https://github.com/mergebase/mergebase-sca/blob/master/src/main/resources/index.jelly#L3

It will be displayed in the Plugin Manager in the Jenkins UI
