### ISSUE TITLE
Request to host gitea-pat-kubernetes-credentials-plugin

### ISSUE THREAD

**Issue by ThisIsQasim** [jenkins-infra/repository-permissions-updater#2479]
### Repository URL

https://github.com/ThisIsQasim/gitea-pat-kubernetes-credentials-plugin

### New Repository Name

gitea-pat-kubernetes-credentials-plugin

### Description

The [Gitea Plugin](https://github.com/jenkinsci/gitea-plugin) has a special credential type for passing the Personal Access Token. This plugin is a [Kubernetes Credentials Provider](https://plugins.jenkins.io/kubernetes-credentials-provider/) adapter of `Gitea Personal Access Token Credential`. It enables a user to setup the Gitea PAT credential by creating a Kubernetes secret with `"jenkins.io/credentials-type": "giteaPAT"` label.

### GitHub users to have commit permission

@thisisqasim

### Jenkins project users to have release permission

thisisqasim

### Issue tracker

GitHub issues

**Comment by ThisIsQasim** [comment]
I have logged into [Artifactory](https://repo.jenkins-ci.org/) almost two hours ago but it is still not picking up the username. Will try again tomorrow.

**Comment by timja** [comment]
1. Please use the latest parent pom not just the minimum. https://github.com/ThisIsQasim/gitea-pat-kubernetes-credentials-plugin/blob/main/pom.xml#L9 https://github.com/jenkinsci/plugin-pom/releases
2. Your package should match the group id io.jenkins.plugins rather than org.jenkinsci.plugins https://github.com/ThisIsQasim/gitea-pat-kubernetes-credentials-plugin/blob/main/src/main/java/org/jenkinsci/plugins/gitea_pat_kubernetes_credentials/GiteaPATCredentialsConvertor.java#L1
3. `Jenkinsfile` should use `buildPlugin()

None of these are blockers so I'll host it now but I suggest you take a look :)

**Comment by ThisIsQasim** [comment]
Thanks @timja I have incorporated all of your suggestions.
