### ISSUE TITLE
paginated-builds

### ISSUE THREAD

**Issue by lineville** [jenkins-infra/repository-permissions-updater#2515]
### Repository URL

https://github.com/lineville/paginated-builds

### New Repository Name

paginated-builds-plugin

### Description

The paginated-builds plugin exposes a new REST API endpoint to access paginated build data for a Jenkins job. Out of the box Jenkins does not provide a method to access build data in pages - you can either get all the builds or the most recent 100 builds. This plugin assists in fetching historical build data for jobs with a large number of builds by being able to request specific pages of historical data.

GET <jenkins_url>/job/<job_name>/builds?start=<build_id>&size=<page_size>&orderBy=<order_by>

- start: The build ID to start from. (1 if not specified)
- size: The number of builds to return. (100 if not specified)
- order_by: The order to return the builds in ("asc" or "desc"). ("desc" if not specified)
- job_name: The name of the Jenkins job to get builds for.
- jenkins_url: The URL of the Jenkins instance.

### GitHub users to have commit permission

@lineville
@luke-engle
@ethanis
@dwhathaway
@MatisseHack
@NateRickard
@j-dunham
@begonaguereca

### Jenkins project users to have release permission

lineville
ethanis
luke_engle

### Issue tracker

GitHub issues

**Comment by lineville** [comment]
The link above to Artifactory ☝️ seems to be broken, the site appears to be down, is there another way the users I've provided under 'Jenkins project users to have release permission' can log into Artifactory so that the request can proceed?

**Comment by timja** [comment]
Nope will need to wait for it to be back up

**Comment by timja** [comment]
Looks generally fine.

A couple of questions,

1. Why do you do a multi-module project when it's just one module? Normally a plugin will put everything in `src` rather than a sub module if another one isn't needed
2. Why do you have the maven release plugin config overridden? It appears to be the default https://github.com/lineville/paginated-builds/blob/main/pom.xml#L86-L96

@Wadeck do you want to review for security?

**Comment by Wadeck** [comment]
Thanks Tim for the ping.

Quick look: you are including snakeyaml directly, I will propose you to change to use https://github.com/jenkinsci/snakeyaml-api-plugin which will allow "us" to update that "api-plugin" and it will be used automatically everywhere. It's the recommended approach. (like you did for jackson2-api)

⚠️ As you copy-pasted multiple classes from other plugins, you have to be warned that such behavior is pretty dangerous in terms of security. If a flaw is detected in one of the class, as you have "forked" them, you will not receive their correction.
(especially [this folder](https://github.com/jenkinsci/pipeline-stage-view-plugin/tree/2de39372527f413351fe8b47c92c306c2c7bfdb8/rest-api/src/main/java/com/cloudbees/workflow/util))

Otherwise my superficial look does not indicate me that a more deeper audit is required, so 🚀

**Comment by timja** [comment]
I can't even see snakeyaml used, and it's just in `dependencyManagement`, could it be removed?

**Comment by daniel-beck** [comment]
This plugin looks like it violates the source's MIT license.

**Comment by Wadeck** [comment]
> This plugin looks like it violates the source's MIT license.

Could you be more specific? not sure to see where. (not a lawyer :D)

**Comment by lineville** [comment]
> Looks generally fine.
> 
> A couple of questions,
> 
> 1. Why do you do a multi-module project when it's just one module? Normally a plugin will put everything in `src` rather than a sub module if another one isn't needed
> 2. Why do you have the maven release plugin config overridden? It appears to be the default https://github.com/lineville/paginated-builds/blob/main/pom.xml#L86-L96
> 
> @Wadeck do you want to review for security?

Thanks for taking a look! To your first question, there isn't a really strong reason that it needed to be in 2 modules, I was following from an existing plugin template that was structured this way and kept it. Happy to simplify it down to 1 module if that helps? To your second question, there also isn't a strong reason from our end that this is there, are you suggesting that block you linked could be omitted?

Also, what are the issues regarding the MIT licensing? Any of the source code that is used here taken from other plugins is under MIT licensing and left as is.

**Comment by timja** [comment]
> Happy to simplify it down to 1 module if that helps?

It's not required but just seemed odd.

>  To your second question, there also isn't a strong reason from our end that this is there, are you suggesting that block you linked could be omitted?

Yes, that would be better, you're overriding any other config that may be set in the parent pom by doing that.

**Comment by daniel-beck** [comment]
> Also, what are the issues regarding the MIT licensing? Any of the source code that is used here taken from other plugins is under MIT licensing and left as is.

The original copyright statements were changed though. AFAIUI (which is admittedly not a lot) that's not good because that's essentially the one requirement.

**Comment by lineville** [comment]
@timja Is it a hard requirement that plugins must require Jenkins version 2.277.1 or higher or is this a recommendation? I was hoping to provide broader compatibility with Jenkins versions as far back as 2.249.1, would this be possible to do or will having a required version lower than 2.277.1 prevent the plugin approval process from moving forward?

**Comment by timja** [comment]
Yes we require that the minimum version is supported by the update center: https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/

anyone running something older than that will struggle to update plugins

**Comment by daniel-beck** [comment]
> anyone running something older than that will struggle to update plugins

For some more color, being on an older release that's no longer supported by update sites makes `hpi:run` and similar very cumbersome, as you often won't be able to install or update plugins using the Plugin Manager. This gets worse over time, of course, but since the oldest supported release usually contains security vulnerabilities that have since been fixed, nobody should run something even older anyway.

**Comment by lineville** [comment]
@daniel-beck Thanks for the explanation, appreciate it, I've set the minimum version to the required 2.277.1 -- looks like it should be good to proceed with review 👍

**Comment by timja** [comment]
Was the licensing issue resolved?

**Comment by lineville** [comment]
Yes, by simplifying it to a single module, and including the `pipeline-stage-view` rest-api plugin as a dependency the licensing is all included in the dependencies and the single license.md file here at the root, since there is no more copy pasted code.

**Comment by lineville** [comment]
I am having a permissions error opening up a PR to the RPU repo 😞 I've opened up an issue for this ☝️ 

@timja 
@Wadeck
