### ISSUE TITLE
Lightstep Incident Response Plugin

### ISSUE THREAD

**Issue by sn-priya-jagyasi** [jenkins-infra/repository-permissions-updater#2516]
### Repository URL

https://github.com/ServiceNow/lightstep-incident-response

### New Repository Name

lightstep-incident-response-plugin

### Description

- We want to host a lightstep-incident-response plugin to integrate Jenkins with Lightstep Incident Response(LIR) application.
- It will enable post-build action namely "Send alerts to Lightstep Incident Response" which when selected gives options to select build status for alert creation on LIR.
- Whenever a build is completed for a Freestyle job, it will post the result to the Lightstep Incident Response application to create alerts.

### GitHub users to have commit permission

@priyajagyasi
@kirannunnasnow

### Jenkins project users to have release permission

priyajagyasi
kirannunnasnow

### Issue tracker

Jira

**Comment by timja** [comment]
Looks okay,

Form databinding seems quite weird in here: https://github.com/ServiceNow/lightstep-incident-response/blob/main/src/main/resources/org/jenkinsci/plugins/lightstepincidentresponse/LightstepWebhookPublisher/config.jelly

You should be able to use the field attribute instead of accessing the instance and setting checked yourself.
The selects should be buildable with `f:select`.

See some of the options here: https://weekly.ci.jenkins.io/design-library/Select/

**Comment by sn-priya-jagyasi** [comment]
@timja I have addressed your feedback and updated the code. Kindly review. Thanks.

**Comment by sn-priya-jagyasi** [comment]
@timja Addressed above points and updated the code.
We are trying to login to artifactory, it says "JFrog platform will be available shortly", is the platform not up?

**Comment by daniel-beck** [comment]
>  We are trying to login to artifactory, it says "JFrog platform will be available shortly", is the platform not up?

Its not, see https://github.com/jenkins-infra/helpdesk/issues/2920

**Comment by sn-priya-jagyasi** [comment]
@daniel-beck when shall we check artifactory back to login? will this request not proceed until the artifactory is up and we are able to login?

**Comment by timja** [comment]
We are waiting for JFrog to get back to us, no ETA as of yet.

We need to wait for it to be back before proceeding

**Comment by sn-priya-jagyasi** [comment]
@timja we have logged in to Artifactory, kindly take this request forward. Thank you.

**Comment by timja** [comment]
@Wadeck any concerns here?

**Comment by Wadeck** [comment]
Superficial audit done. Nothing to report.

@sn-priya-jagyasi For your information, in the [`perform`](https://github.com/ServiceNow/lightstep-incident-response/blob/22d74c59a8cbe2aac9ef39f7bd73ea1754246533/src/main/java/org/jenkinsci/plugins/lightstepincidentresponse/LightstepWebhookPublisher.java#L55) method of a Notifier, you have the possibility to execute the code from [LightstepJobListener](https://github.com/ServiceNow/lightstep-incident-response/blob/main/src/main/java/org/jenkinsci/plugins/lightstepincidentresponse/LightstepJobListener.java) instead of listening to all jobs, and then filtering. That's perhaps more efficient and more clean I imagine 💡

**Comment by sn-priya-jagyasi** [comment]
@Wadeck do you have any sample code for listening jobs in perform method of notifier, that we can refer to?

**Comment by Wadeck** [comment]
@sn-priya-jagyasi are you sure that you need to listen to jobs? from my understanding you can just put your code inside the Notifier instead of having a listener that is listening to all jobs and checking if one has the expected notifier. The Notifier#perform method is called when the regular Build steps are done, you can check the same kind of information at that moment. Your approach seems just more complicated.

How to find implementation samples:
- https://www.jenkins.io/doc/developer/extensions/ 
- => https://www.jenkins.io/doc/developer/extensions/jenkins-core/
- => https://www.jenkins.io/doc/developer/extensions/jenkins-core/#notifier
  - [MonitorPublisher](https://github.com/jenkinsci/statusmonitor-plugin/blob/38607e77fa77a6288361b2a4e18393f84d174ada/src/main/java/hudson/plugins/statusmonitor/MonitorPublisher.java#L36-L39)
  - [PostBuildCleanup](https://github.com/jenkinsci/proc-cleaner-plugin/blob/a11f38b2e7b11a749b93908c0edaba9040e8d24d/src/main/java/org/jenkinsci/plugins/proccleaner/PostBuildCleanup.java#L55-L58)
  - [BuildTrigger](https://github.com/jenkinsci/parameterized-trigger-plugin/blob/522340994295982637a0ee5777113c325c4bc9c2/src/main/java/hudson/plugins/parameterizedtrigger/BuildTrigger.java#L69)

**Comment by priya-jagyasi** [comment]
@Wadeck I have done suggested changes, kindly review.

**Comment by priya-jagyasi** [comment]
Hi @Wadeck , could you please review the updated code.

**Comment by Wadeck** [comment]
@priya-jagyasi Hey, you replied 6 days after my last comment, second ping after less than 48h is not "fair" ;-)

From my PoV the changes are ok 👍

**Comment by priya-jagyasi** [comment]
Thanks @Wadeck , what is the next step?

**Comment by Wadeck** [comment]
@timja back to you 👍

**Comment by priya-jagyasi** [comment]
Thanks @timja for taking this ahead. The document https://www.jenkins.io/doc/developer/publishing/documentation/ says that plugin doc on [plugins.jenkins.io](plugins.jenkins.io)  will be picked up from README file...could you pls let us know how to get a plugin page for our plugin? Also, how can we edit it in the future?

**Comment by priya-jagyasi** [comment]
Hi @timja, Few things below:

- I don't see lightstep-incident-response-plugin component in jira yet, could you please provide the link to it.
- [Accept the invitation to the Jenkins CI Org on Github](https://github.com/jenkinsci) - how should we do this? Please guide.
- [Releasing your plugin](https://jenkins.io/doc/developer/publishing/releasing/) - Could you let us know what is needed from our side in order to release the plugin.
- Could you pls give upload permissions to AshutoshSNow and kirannunnaSNOW. These users have logged in to Artifactory

**Comment by timja** [comment]
> * I don't see lightstep-incident-response-plugin component in jira yet, could you please provide the link to it.

Not sure how to provide a link but it exists:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/21194782/168972921-dd0fc46e-451c-414e-a0bc-5fde44ffee59.png">

> [Accept the invitation to the Jenkins CI Org on Github](https://github.com/jenkinsci) - how should we do this? Please guide.

There will be a big yellow banner at the top if you aren't a member of the jenkinsci organisation, accept the invite there

> Could you let us know what is needed from our side in order to release the plugin.

Read the guides they should have all the information you need or post to the Jenkins developer mailing list




> * Could you pls give upload permissions to AshutoshSNow and kirannunnaSNOW. These users have logged in to Artifactory

Send a pull request to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-lightstep-incident-response.yml to add them
