### ISSUE TITLE
Host plugin aws-sqs-trigge plugin

### ISSUE THREAD

**Issue by topikachu** [jenkins-infra/repository-permissions-updater#2569]
### Repository URL

https://github.com/topikachu/aws-sqs-trigger-plugin

### New Repository Name

aws-sqs-trigger-plugin

### Description

This is a "simple" SQS plugin that doesn't require any other dependencies, ( for example the CodeCommit).
It just watches the queue and triggers build when receiving the message(s).

### GitHub users to have commit permission

@topikachu 

### Jenkins project users to have release permission

topikachu

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by timja** [comment]
Hi

1. You bom version should match the Jenkins LTS line you are targeting (2.277) you've currently got [2.249](https://github.com/topikachu/aws-sqs-trigger-plugin/blob/b865528a3b6f2fffb1d07789db0c1d8202c48213/pom.xml#L51)
2. Please use the [jackson2-api-plugin](https://plugins.jenkins.io/jackson2-api/#dependencies) instead of including [jackson-dataformat-cbor](https://github.com/topikachu/aws-sqs-trigger-plugin/blob/b865528a3b6f2fffb1d07789db0c1d8202c48213/pom.xml#L63-L67) directly. See [Using library wrapper plugins](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#using-library-wrapper-plugins) for more information.

**Comment by topikachu** [comment]
> https://github.com/topikachu/aws-sqs-trigger-plugin

Yes sir! ^-^
BOM is updated to 2.277.
Remove the Jackson lib which is not used now.

**Comment by topikachu** [comment]
> 



> Hi
> 
> 1. You bom version should match the Jenkins LTS line you are targeting (2.277) you've currently got [2.249](https://github.com/topikachu/aws-sqs-trigger-plugin/blob/b865528a3b6f2fffb1d07789db0c1d8202c48213/pom.xml#L51)
> 2. Please use the [jackson2-api-plugin](https://plugins.jenkins.io/jackson2-api/#dependencies) instead of including [jackson-dataformat-cbor](https://github.com/topikachu/aws-sqs-trigger-plugin/blob/b865528a3b6f2fffb1d07789db0c1d8202c48213/pom.xml#L63-L67) directly. See [Using library wrapper plugins](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#using-library-wrapper-plugins) for more information.
Yes sir! ^-^
BOM is updated to 2.277.
Remove the Jackson lib which is not used now.

**Comment by timja** [comment]
Ok just pending security team confirmation now

**Comment by Wadeck** [comment]
Superficial audit done, thanks for the submission.

The plugin is using the expected `@POST` and permission checks, fine with me!
