### ISSUE TITLE
OES Template Plugin

### ISSUE THREAD

**Issue by seanly** [jenkins-infra/repository-permissions-updater#2580]
### Repository URL

https://github.com/opsbox-dev/oes-template-plugin

### New Repository Name

oes-template-plugin

### Description

OES Template plugin is a simple implementation of the pipeline template to help user simplify job configuration.

### GitHub users to have commit permission

@seanly 

### Jenkins project users to have release permission

seanly

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by timja** [comment]
You're missing the plugin description file (src/main/resources/index.jelly) that is shown in the plugin manager:
e.g. https://github.com/jenkinsci/dark-theme-plugin/blob/master/src/main/resources/index.jelly

https://github.com/opsbox-dev/oes-template-plugin/tree/master/src/main/resources

**Comment by seanly** [comment]
thanks @timja and @Wadeck , I have added plugin description file.

**Comment by Wadeck** [comment]
Due to the feature it proposes, it will require deep audit. Tracked internally as JENSEC-1837. Due to the other security audits / corrections we are currently on, I cannot promise a very short ETA.

**Comment by yaroslavafenkin** [comment]
Hi @seanly,

Here's some feedback for you:

* RCE in [AttributeInjector.java#L62](https://github.com/opsbox-dev/oes-template-plugin/blob/94baa10e695f4fc0c81d0c6911a3476dc40a4dd1/src/main/java/cn/opsbox/jenkinsci/plugins/cps/AttributeInjector.java#L62). We've tested it with a slightly tweaked version of [jordyv/poc-snakeyaml](https://github.com/jordyv/poc-snakeyaml).

A known way to remediate the problem is to use `new Yaml(new SafeConstructor())` instead of no-arg constructor.

---
* Vulnerable dependency: `com.google.guava:guava` ([CVE-2018-10237](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10237), [CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908)).

It doesn't seem to have any impact on the plugin though. There's a single usage of guava here: [AttributeInjector.java#L46](https://github.com/opsbox-dev/oes-template-plugin/blob/fbc8d4ad25bfd20d2c713fb6ee0802f807220437/src/main/java/cn/opsbox/jenkinsci/plugins/cps/AttributeInjector.java#L46), which can easily be replaced by non-guava code. So we'd recommend to do that and get rid of the dependency completely.

---
Please address our findings and let us know when you're done or if you have any questions.

**Comment by daniel-beck** [comment]
FTR https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions (the hosting checker seems to be a bit too permissive there).

Also, I recommend aligning the BOM version and the core dependency.

**Comment by seanly** [comment]
It has been modified, commit log:  https://github.com/opsbox-dev/oes-template-plugin/commit/dc878d1a99168ab308b238475f21de66d938c12e

> Hi @seanly,
> 
> Here's some feedback for you:
> 
> * RCE in [AttributeInjector.java#L62](https://github.com/opsbox-dev/oes-template-plugin/blob/94baa10e695f4fc0c81d0c6911a3476dc40a4dd1/src/main/java/cn/opsbox/jenkinsci/plugins/cps/AttributeInjector.java#L62). We've tested it with a slightly tweaked version of [jordyv/poc-snakeyaml](https://github.com/jordyv/poc-snakeyaml).
> 
> A known way to remediate the problem is to use `new Yaml(new SafeConstructor())` instead of no-arg constructor.
> 
> * Vulnerable dependency: `com.google.guava:guava` ([CVE-2018-10237](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10237), [CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908)).
> 
> It doesn't seem to have any impact on the plugin though. There's a single usage of guava here: [AttributeInjector.java#L46](https://github.com/opsbox-dev/oes-template-plugin/blob/fbc8d4ad25bfd20d2c713fb6ee0802f807220437/src/main/java/cn/opsbox/jenkinsci/plugins/cps/AttributeInjector.java#L46), which can easily be replaced by non-guava code. So we'd recommend to do that and get rid of the dependency completely.
> 
> Please address our findings and let us know when you're done or if you have any questions.

**Comment by daniel-beck** [comment]
@yaroslavafenkin FYI

**Comment by yaroslavafenkin** [comment]
Re-checked, issue is fixed. Dependencies also look good now 👍
