### ISSUE TITLE
Microsoft Teams Notifier

### ISSUE THREAD

**Issue by huynxtb** [jenkins-infra/repository-permissions-updater#2614]
### Repository URL

https://github.com/huynxtb/jenkins-plugins-ms-teams-notifier

### New Repository Name

microsoft-teams-notifier-plugin

### Description

Microsoft Teams Notifier provides a bridge between Jenkins and Microsoft Teams through the built-in webhook functionality:
- Get success and fail messages about your job
- Link to build artifacts
Please read more information in my repository.

### GitHub users to have commit permission

huynxtb

### Jenkins project users to have release permission

huynx11

### Issue tracker

GitHub issues

**Comment by timja** [comment]
Can you clarify the difference between this plugin and https://plugins.jenkins.io/Office-365-Connector/ ?

Is there a reason that that plugin can't be enhanced?

**Comment by huynxtb** [comment]
Dear Tim,

Office-365-Connector is a good tool but I find it quite complicated to set
up.
Moreover, it has quite a bit of information for the user. so I made a
similar one hoping to solve those problems. I'm not saying mine is better,
but I do it because I want to give users more choice. And the notification
message also looks clearer.

Vào Th 6, 24 thg 6, 2022 lúc 14:41 Tim Jacomb ***@***.***> đã
viết:

**Comment by huynxtb** [comment]
> Can you clarify the difference between this plugin and https://plugins.jenkins.io/Office-365-Connector/ ?
> 
> Is there a reason that that plugin can't be enhanced?

**Comment by timja** [comment]
cc @Wadeck

**Comment by Wadeck** [comment]
@huynxtb 
*Non-security issue:*
- Your usage of [Validation.java#L3](https://github.com/huynxtb/jenkins-plugins-ms-teams-notifier/blob/eff0206c0615920d1bfca9db8053b7b4e324bdc4/src/main/java/io/jenkins/plugins/util/Validation.java#L3) is restricted, meaning that this API is not guaranteed to be kept in Jenkins core. You can use it if you want, but at your own risk. My advice would be to just check for the scheme
- I am not sure the license copyright is correct: [LICENSE.md](https://github.com/huynxtb/jenkins-plugins-ms-teams-notifier/blob/eff0206c0615920d1bfca9db8053b7b4e324bdc4/LICENSE.md?plain=1#L3)

Otherwise in terms of security, it's fine :-)

**Comment by huynxtb** [comment]
Dear @Wadeck,
That is my fault. I have resolved it. So can you recheck for it. Thank you!
