### ISSUE TITLE
AWS EKS Token Plugin

### ISSUE THREAD

**Issue by topikachu** [jenkins-infra/repository-permissions-updater#2654]
### Repository URL

https://github.com/topikachu/eks-token-plugin

### New Repository Name

eks-token-plugin

### Description

This is a plugin to generate AWS EKS tokens.
AWS EKS requires an AWS IAM credentials and AWS CLI to generate a token. This plugin integrates with the [](https://plugins.jenkins.io/aws-credentials/) to generate a correct EKS token.
A use case is to use this plugin with [Jenkins Kubernetes Plugin](https://plugins.jenkins.io/kubernetes/) to create dynamic build agent pod in any EKS cluster.

### GitHub users to have commit permission

@topikachu 

### Jenkins project users to have release permission

topikachu 

### Issue tracker

GitHub issues

**Comment by timja** [comment]
Cc @Wadeck

**Comment by yaroslavafenkin** [comment]
@topikachu,

[EksTokenCredentials.java#L133](https://github.com/topikachu/eks-token-plugin/blob/4688e130fb631e9591634c42ef379b9dc94d88e1/src/main/java/io/jenkins/plugins/eks_token_plugin/EksTokenCredentials.java#L133) should be guarded by a permission check, otherwise low privileged users can obtain credential IDs.
Please refer to https://www.jenkins.io/doc/developer/security/form-validation/#checking-permissions.

Also, not sure what are your plans on [EksTokenCredentials/config.jelly#L17-L19](https://github.com/topikachu/eks-token-plugin/blob/4688e130fb631e9591634c42ef379b9dc94d88e1/src/main/resources/io/jenkins/plugins/eks_token_plugin/EksTokenCredentials/config.jelly#L17-L19). If you're going to implement `doTestConnection` it would have to be guarded by a permission check too.

**Comment by topikachu** [comment]
> @topikachu,
> 
> [EksTokenCredentials.java#L133](https://github.com/topikachu/eks-token-plugin/blob/4688e130fb631e9591634c42ef379b9dc94d88e1/src/main/java/io/jenkins/plugins/eks_token_plugin/EksTokenCredentials.java#L133) should be guarded by a permission check, otherwise low privileged users can obtain credential IDs. Please refer to https://www.jenkins.io/doc/developer/security/form-validation/#checking-permissions.
> 
> Also, not sure what are your plans on [EksTokenCredentials/config.jelly#L17-L19](https://github.com/topikachu/eks-token-plugin/blob/4688e130fb631e9591634c42ef379b9dc94d88e1/src/main/resources/io/jenkins/plugins/eks_token_plugin/EksTokenCredentials/config.jelly#L17-L19). If you're going to implement `doTestConnection` it would have to be guarded by a permission check too.


The issue is fixed.
doTestConnection is removed.

Thanks
