### ISSUE TITLE
Levo Plugin Hosting Request (https://levo.ai)

### ISSUE THREAD

**Issue by mgiamberardino** [jenkins-infra/repository-permissions-updater#2679]
### Repository URL

https://github.com/levoai/jenkins-levo-plugin

### New Repository Name

levo-plugin

### Description

This is a plugin to be able to run security test plans from [Levo AI](https://levo.ai ). 

### GitHub users to have commit permission

@mgiamberardino
@amitpl
@buchi-busireddy
@jchamarthi-levo

### Jenkins project users to have release permission

mauroatlevo

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by yaroslavafenkin** [comment]
CERT will have a deeper look. Tracked internally as JENSEC-1868.

**Comment by mgiamberardino** [comment]
Thanks, @yaroslavafenkin. Can I have tracking of the status of that ticket somehow? Is that part of the Jenkins JIRA?

**Comment by Wadeck** [comment]
It's a CloudBees internal ticket system, we usually do the audit within 5 working days :)

**Comment by mgiamberardino** [comment]
Cool 😃 Thanks @Wadeck for the quick response.

**Comment by yaroslavafenkin** [comment]
Hi @mgiamberardino,

we're back with some feedback for you.

As of time the audit was performed (https://github.com/levoai/jenkins-levo-plugin/commit/ea96709fb2c3de0fbcd4910bda4e436c867ca947) there are several issues with building the plugin.
First one that pops up is:
```
Dependency org.jenkins-ci.plugins:ssh-credentials:jar:277.280.v1e86b_7d0056b_ requires Jenkins 2.319.3 or higher.
```
Bumping up the core version in pom.xml to 2.319.3 reveals another issue:
```
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.29:hpi (default-hpi) on project levo: Missing /jenkins-levo-plugin/target/classes/index.jelly. Delete any <description> from pom.xml and create src/main/resources/index.jelly
```
Misplaced `index.jelly` it is.
Resolving it reveals that there are few spotbugs issues:
```
[ERROR] High: Found reliance on default encoding in io.jenkins.plugins.levo.TestPlanBuilder.perform(Run, FilePath, EnvVars, Launcher, TaskListener): new java.io.InputStreamReader(InputStream) [io.jenkins.plugins.levo.TestPlanBuilder] At TestPlanBuilder.java:[line 113] DM_DEFAULT_ENCODING
[ERROR] Medium: io.jenkins.plugins.levo.TestPlanBuilder.perform(Run, FilePath, EnvVars, Launcher, TaskListener) may fail to close stream [io.jenkins.plugins.levo.TestPlanBuilder] At TestPlanBuilder.java:[line 113] OS_OPEN_STREAM
[ERROR] High: Found reliance on default encoding in io.jenkins.plugins.levo.helpers.LevoDockerTool.runLevoTestPlan(Run, Launcher, EnvVars, EnvVars, String, String, String, String): new java.io.FileWriter(String, boolean) [io.jenkins.plugins.levo.helpers.LevoDockerTool] At LevoDockerTool.java:[line 96] DM_DEFAULT_ENCODING
[ERROR] High: io.jenkins.plugins.levo.helpers.LevoDockerTool.CLIENT_TIMEOUT isn't final but should be [io.jenkins.plugins.levo.helpers.LevoDockerTool] At LevoDockerTool.java:[line 39] MS_SHOULD_BE_FINAL
[ERROR] Medium: Possible null pointer dereference in io.jenkins.plugins.levo.helpers.LevoDockerTool.buildLevoCommand(Run, Launcher, EnvVars, EnvVars, String) due to return value of called method [io.jenkins.plugins.levo.helpers.LevoDockerTool, io.jenkins.plugins.levo.helpers.LevoDockerTool] Dereferenced at LevoDockerTool.java:[line 42]Known null at LevoDockerTool.java:[line 42] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
```

[LevoCLICredentialsImpl/credentials.jelly#L22-L24](https://github.com/levoai/jenkins-levo-plugin/blob/64f198f3485f30ceb3503dc6b7717a024a8a60e6/src/main/resources/io/jenkins/plugins/levo/credentials/LevoCLICredentialsImpl/credentials.jelly#L22-L24) has an issue. Because you have `field="authorizationKey"` there, Stapler under the hood would try to invoke a method named `getAuthorizationKey` attempting to populate the field when configuring an existing entry. [LevoCLICredentialsImpl.java](https://github.com/levoai/jenkins-levo-plugin/blob/64f198f3485f30ceb3503dc6b7717a024a8a60e6/src/main/java/io/jenkins/plugins/levo/credentials/LevoCLICredentialsImpl.java) only has a method called `getCLIAuthorizationKey`, and Stapler will fail to find that and won’t populate the input box. Simply resaving credentials configuration without providing a valid authKey would override it with an empty value, making it easy to overlook and override valid authKey by accident. Renaming the method to `getAuthorizationKey` will allow Stapler to get the current value of a field, making an existing entry look like this:

![image](https://user-images.githubusercontent.com/91559310/182884687-7603b90f-f15c-49e8-9c06-918283740236.png)
instead of 
![image](https://user-images.githubusercontent.com/91559310/182884787-2fd4bf4b-8e57-49cd-a6bb-1de4ba8e622f.png)

[LevoCLICredentialsImpl.java#L31-L35](https://github.com/levoai/jenkins-levo-plugin/blob/64f198f3485f30ceb3503dc6b7717a024a8a60e6/src/main/java/io/jenkins/plugins/levo/credentials/LevoCLICredentialsImpl.java#L31-L35) constructor takes `authorizationKey` as String, and then does `Secret.fromString(authorizationKey)`. This makes it that `authorizationKey` is transmitted as plain text, instead of its encrypted form. In addition this would re-encrypt the value every time configuration is saved, even if the value hasn’t changed, which isn't a security issue in itself, but there's no reason to do it.

Please address these issues and let us know when you are done. If you have any further questions please feel free to ask.

**Comment by mgiamberardino** [comment]
Hi @yaroslavafenkin.

We need to build it with support for 2.319.1. 
After raising this request I merged some suggestions from the bot in the repo. I'm wondering if the `ssh-credentials` dependency is something introduced with the upgrade of the parent pom from 2.41 to 2.44. If so we can revert that change.

Could you tell me if this is so?

Thanks

**Comment by daniel-beck** [comment]
> I merged some suggestions from the bot in the repo. I'm wondering if the `ssh-credentials` dependency is something introduced with the upgrade of the parent pom from 4.41 to 4.44.

https://github.com/levoai/jenkins-levo-plugin/blob/ea96709fb2c3de0fbcd4910bda4e436c867ca947/pom.xml#L59 -> https://plugins.jenkins.io/docker-commons/#dependencies -> https://plugins.jenkins.io/credentials-binding/#dependencies -> https://plugins.jenkins.io/ssh-credentials/

**Comment by mgiamberardino** [comment]
Hi @daniel-beck.

Thanks for the quick response. I'll push the changes by using 2.319.3 as it's recommended.

**Comment by mgiamberardino** [comment]
Hi, @yaroslavafenkin @daniel-beck,

These are the [changes](https://github.com/levoai/jenkins-levo-plugin/pull/9/files) that were merged to address these comments. Please let me know if there are any further issues.

Also if you can share the spotbugs config you use to run against the plugins it would be great. I would like to run that as part of pre-commit hooks.

Thanks!

**Comment by yaroslavafenkin** [comment]
@mgiamberardino,

Spotbugs runs as a part of `verify` phase as defined in https://github.com/jenkinsci/plugin-pom/blob/plugin-4.44/pom.xml#L694. You could run `mvn verify` locally before pushing, but CI builds will do that for you anyway :)

Another issue I've just noticed is that `io/jenkins/plugins/levo/credentials/LevoCLICredentialsImpl/credentials.jelly` is missing `<?jelly escape-by-default='true'?>` on top. Sorry for not pointing that out earlier.

Other corrections look reasonable to me 👍

**Comment by mgiamberardino** [comment]
@yaroslavafenkin 

> Spotbugs runs as a part of `verify` phase as defined in https://github.com/jenkinsci/plugin-pom/blob/plugin-4.44/pom.xml#L694. You could run `mvn verify` locally before pushing, but CI builds will do that for you anyway :)

Cool, thanks!

> Another issue I've just noticed is that `io/jenkins/plugins/levo/credentials/LevoCLICredentialsImpl/credentials.jelly` is missing `<?jelly escape-by-default='true'?>` on top. Sorry for not pointing that out earlier.

Don't worry. [Changes](https://github.com/levoai/jenkins-levo-plugin/pull/10) to address this has been merged.

Thanks.

**Comment by yaroslavafenkin** [comment]
LGTM.

@timja, you can proceed.
