### ISSUE TITLE
custom-environment

### ISSUE THREAD

**Issue by yh1094632455** [jenkins-infra/repository-permissions-updater#2815]
### Repository URL

https://github.com/yh1094632455/custom-environment

### New Repository Name

custom-environment-plugin

### Description

For example, each of our users has their own internal platform account and password for use in the build task, so that each user can set their own username and password and use it in the build task, and finally pass it to, for example, python to do something Access to internal git repositories and internal publishing platform things

### GitHub users to have commit permission

yh1094632455

### Jenkins project users to have release permission

xhh

### Issue tracker

Jira

**Comment by yaroslavafenkin** [comment]
Jenkins CERT will have a deeper look.

**Comment by yaroslavafenkin** [comment]
Hi @yh1094632455,

We've had a look at the plugin.
If we understand it correctly the functionality your plugin implements is already (maybe partially) present in such plugins as [envinject](https://plugins.jenkins.io/envinject/) and [mask-passwords](https://plugins.jenkins.io/mask-passwords/). Are you familiar with those? If so, what's the functionality your plugin has that those two don't have?

**Comment by yh1094632455** [comment]
@yaroslavafenkin 
In my plug-in, each user can set some environment variables, and then obtain the environment variables set by the user according to the user running the task when building the task. If the construction task using Generic Webhook Trigger is in accordance with the format, Cause can also match the user and then take the user's own environment variables to process something, such as Git Webhook push code for Jenkins construction. We can build according to the name of the user who pushes the code to obtain information set by the user, not limited to the password and so on

**Comment by yh1094632455** [comment]
Hi @yaroslavafenkin 
I have fixed the above issues, added a description and plug-in support pipeline

**Comment by yaroslavafenkin** [comment]
Plain text password storage is fixed.

---

Since you use `EnvironmentContributor` to inject variables you don't need `CustomenvironmentBuilder` that implements `SimpleBuildStep`. You can move `BuildUserVarsEnvironmentContributor` and the associated code to a separate class and remove any code related to `SimpleBuildStep`.
Note that it's not a common practice to use `EnvironmentContributor` to inject variables containing sensitive data. Those variables will not be masked in the output log. Consider adding a warning to the documentation saying that it's the case and that the feature should be used with caution.

**Comment by yh1094632455** [comment]
Hi @yaroslavafenkin  
Thank you. I have updated the code to fix the problem you mentioned above

**Comment by dwnusbaum** [comment]
@yh1094632455 Yaroslav and I have been discussing this a bit. We recommend that you delete the copy of `MaskPasswordsOutputStream` from your plugin and instead update your readme to indicate that users should use plugins like https://plugins.jenkins.io/mask-passwords/ to mask any secrets defined by the plugin. When using Freestyle jobs, that plugin is the standard way to mask raw `Secret`s in build logs. When using Pipeline, there are various other contexts that need to be considered and your code does not handle correctly and cannot easily be updated to do so.

In general, I would really recommend considering more drastic changes to the design of your plugin. It is almost always preferable to integrate with [Credentials](https://plugins.jenkins.io/credentials/) plugin rather than using `Secret` directly, especially for secrets that are used in builds and may end up in builds logs. That way, Jenkins users can bind secrets using [Credentials Binding](https://plugins.jenkins.io/credentials-binding/) plugin, which is essentially the only supported and maintained way to mask credentials in Jenkins. It handles many more cases than the basic `MaskPasswordsOutputStream` in your plugin, see for example [these classes](https://github.com/jenkinsci/credentials-binding-plugin/tree/0d357c672c22b8685ac7a911a315213c594ac38f/src/main/java/org/jenkinsci/plugins/credentialsbinding/masking) which go to special lengths to mask variations of passwords that might be displayed when passwords are used in different context. Copying `MaskPasswordsOutputStream` or other classes like it into your plugin is an indication that your plugin's design is not ideal.

That said, I am struggling to understand the use case for this plugin. Between parameterized builds (build parameters are automatically bound as environment variables), https://plugins.jenkins.io/envinject/, https://plugins.jenkins.io/build-user-vars-plugin/, and https://plugins.jenkins.io/mask-passwords/, it seems like there are various ways to obtain very similar functionality. Could you update one of those plugins instead to add new functionality?

For example, a user could set up a build with a credentials parameter that allows user scope credentials, and then users could define credentials in their own accounts and select those credentials when launching a build. Admins would also still be able to define a globally-defined credential that could be used if needed. The credential would be bound using Credentials Binding plugin and all masking would be taken care of properly.

**Comment by NotMyFault** [comment]
Hey @yh1094632455,

do you mind addressing the open concerns, please?

**Comment by NotMyFault** [comment]
@yh1094632455 If you are still interested in continuing with this hosting request, please address the outstanding concerns and re-open the request.

Thanks!
