### ISSUE TITLE
Codethreat Scanner Plugin

### ISSUE THREAD

**Issue by thyldrm** [jenkins-infra/repository-permissions-updater#3123]
### Repository URL

https://github.com/CodeThreat/codethreat-jenkins-plugin

### New Repository Name

codethreat-scanner-plugin

### Description

The Jenkins integration plugin allows users to integrate their CodeThreat SAST server. This integration enables users to automate the process of running security scans on their applications as part of their CI/CD pipeline. With the plugin, users can easily configure and trigger SAST scans from within Jenkins, receive notifications of any security vulnerabilities found, and view the results directly. This streamlines the application security testing process, reducing the time and effort required to manually run security scans and enabling developers to quickly address any security issues that are discovered.

### GitHub users to have commit permission

@thyldrm
@sust4in

### Jenkins project users to have release permission

codethreat

### Issue tracker

GitHub issues

**Comment by daniel-beck** [comment]
Is https://github.com/jenkins-infra/repository-permissions-updater/issues/3121 obsolete?

**Comment by thyldrm** [comment]
Yes.

**Comment by Kevin-CB** [comment]
Hello @thyldrm, 

We were able to perform a more complete audit on your plugin, here are some feedbacks:

- You’re storing sensible variable in clear [CodeThreatBuilder.java#L76](https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/src/main/java/io/jenkins/plugins/sample/CodeThreatBuilder.java#L76) & [CodeThreatBuilder.java#L81](https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/src/main/java/io/jenkins/plugins/sample/CodeThreatBuilder.java#L81). For freestyle projects you should use the Secret type to avoid storing them in plain text. And for pipelines, you should use a credentialsId to avoid getting them stored.
Recommendation: https://www.jenkins.io/doc/developer/security/secrets/ 

- There is an arbitrary file read vulnerability at [CodeThreatBuilder.java#L197](https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/src/main/java/io/jenkins/plugins/sample/CodeThreatBuilder.java#L197), you should not use it in the constructor but in your perform method, with the [FilePath](https://javadoc.jenkins.io/hudson/FilePath.html) class and a path validation. Alos, you should not use File directly in your pipeline, allowing the File signature can open the way to more severe vulnerabilities.

- There are probably XSS vulnerabilities with [CodeThreatBuilder.java#L622-L716](https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/src/main/java/io/jenkins/plugins/sample/CodeThreatBuilder.java#L622-L716), all variables inserted in HTML need to be trusted (any user's variables, even coming from your application is not trusted), if they’re not, you’ve to escape them.
To avoid so much HTML concatenation, you can try to build your table directly in Jelly e.g: [index.jelly#L65-L69](https://github.com/yaroslavafenkin/junit-plugin/blob/4ba5a491583157a90bfd472db5f657a60bb0c38e/src/main/resources/hudson/tasks/junit/CaseResult/index.jelly#L65-L69)
Jenkins have APIs plugins that you should instead of [pom.xml#L73-L97](https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/master/pom.xml#L73-L97).

- You’ve multiple dependencies with known vulnerabilities:

  - [CVE-2019-17571](https://nvd.nist.gov/vuln/detail/CVE-2019-17571) -> ctct@1.0-SNAPSHOT > log4j:log4j@1.2.17

  - [CVE-2022-23307](https://nvd.nist.gov/vuln/detail/CVE-2022-23307) -> ctct@1.0-SNAPSHOT > log4j:log4j@1.2.17
  - [CVE-2022-23302](https://nvd.nist.gov/vuln/detail/CVE-2022-23302) -> ctct@1.0-SNAPSHOT > log4j:log4j@1.2.17
  - [SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044](https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044) -> ctct@1.0-SNAPSHOT > com.squareup.okhttp3:okhttp@3.14.2
  - [CVE-2020-36518](https://nvd.nist.gov/vuln/detail/CVE-2020-36518) -> ctct@1.0-SNAPSHOT > com.fasterxml.jackson.core:jackson-databind@2.11.3
  - [CVE-2022-23305](https://nvd.nist.gov/vuln/detail/CVE-2022-23305) -> ctct@1.0-SNAPSHOT > log4j:log4j@1.2.17
  - [SNYK-JAVA-ORGJSON-2841369](https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-2841369) -> ctct@1.0-SNAPSHOT > org.json:json@20160810
  - [CVE-2021-4104](https://nvd.nist.gov/vuln/detail/CVE-2021-4104) -> ctct@1.0-SNAPSHOT > log4j:log4j@1.2.17
  - [CVE-2022-42004](https://nvd.nist.gov/vuln/detail/CVE-2022-42004) -> ctct@1.0-SNAPSHOT > com.fasterxml.jackson.core:jackson-databind@2.11.3
  - [CVE-2022-42003](https://nvd.nist.gov/vuln/detail/CVE-2022-42003) -> ctct@1.0-SNAPSHOT > com.fasterxml.jackson.core:jackson-databind@2.11.3
  - [CVE-2022-25647](https://nvd.nist.gov/vuln/detail/CVE-2022-25647) -> ctct@1.0-SNAPSHOT > com.google.code.gson:gson@2.8.6
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698 -> ctct@1.0-SNAPSHOT > com.fasterxml.jackson.core:jackson-databind@2.11.3
  - [CVE-2020-9488](https://nvd.nist.gov/vuln/detail/CVE-2020-9488) -> ctct@1.0-SNAPSHOT > log4j:log4j@1.2.17

I will let you correct the different findings and ping us when you are done or if you have security related questions.

**Comment by thyldrm** [comment]
Hello,

Thank you for your feedback. I think if an update is made for the packages you mentioned, the issues will be resolved. Also, is it necessary to update the other 3 items?

**Comment by yaroslavafenkin** [comment]
> is it necessary to update the other 3 items

If you are referring to cleartext secrets storage, XSS and arbitrary file read vulnerabilities, then yes, it is necessary to address those before we can proceed with the hosting.

**Comment by NotMyFault** [comment]
Hey @thyldrm,

alongside the open security issues, I have some general feedback for the hosting proposal:
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/pom.xml#L73-L77 instead of shading okhttp yourself, you can depend on the Jenkins plugin equivalent providing the functionality: https://plugins.jenkins.io/okhttp-api/#dependencies
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/pom.xml#L78-L82 instead of shading jackson components, you can depend on the Jenkins plugin equivalent: https://plugins.jenkins.io/jackson2-api/#dependencies
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/pom.xml#L94-L98 appears to be unused because you use the standard Jenkins logger, and therefore you should remove it from your pom.
- https://github.com/CodeThreat/codethreat-jenkins-plugin/tree/master/src/main/java/io/jenkins/plugins/sample I recommend moving your classes out of the `/sample/` structure to io.jenkins.plugins.codethreatscanner or a better matching location. The same applies to the test and resource files.
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/master/src/main/resources/index.jelly Please provide some information what this plugin is for and what it does.
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/0b5e85f64cfc4cba7987f7db13cbaa7117932c7a/src/main/java/io/jenkins/plugins/sample/CodeThreatBuilder.java#L622-L716 instead of in lining HTML and CSS, I recommend using Jelly files to design the layout of your view and CSS files to declare additional decoration to be used in your Jelly files, which then are used to generate the layout the end user will face.
This is the standard approach how to work with views in Jenkins, instead of manually parsing plain html data.

**Comment by thyldrm** [comment]
Hi, Thanks again for your feedback. All of the items you mentioned have been corrected appropriately.

**Comment by yaroslavafenkin** [comment]
@thyldrm,

Things Kevin has mentioned above seem to be addressed.
There's still something not security related that caught my attention:
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/3ae8e72d236a044fd89678a24e1b2a882fdd5fea/src/main/java/io/jenkins/plugins/CodeThreatBuilder.java#L573
You should probably pass `credentialsId` as an argument to your step instead of expecting a hardcoded one.
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/3ae8e72d236a044fd89678a24e1b2a882fdd5fea/src/main/java/io/jenkins/plugins/CodeThreatBuilder.java#L581, `/private` prefix here is questionable. Can you elaborate a bit why do you need it?

**Comment by thyldrm** [comment]
-Should the user send an argument named `credentialsId` from the pipeline?

-I'm doing a file path check with getCanonicalPath() . Because getCanonicalPath() sees the `/var` file, it adds the prename `/private.` For this reason, compare always fails.

**Comment by yaroslavafenkin** [comment]
> Should the user send an argument named credentialsId from the pipeline?

That would be my expectation.

> Because `getCanonicalPath()` sees the `/var` file, it adds the prename `/private`

Isn't `/private` specific to OS X? Would that comparison work on Windows or Linux?

---
Another thing I forgot to mention in the previous comment.
In pom you declare a dependency on [`cloudbees-credentials`](https://plugins.jenkins.io/cloudbees-credentials/) plugin (https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/master/pom.xml#L96-L100) which is deprecated. You probably want to use [credentials](https://plugins.jenkins.io/credentials/) instead.

**Comment by yaroslavafenkin** [comment]
[This change](https://github.com/CodeThreat/codethreat-jenkins-plugin/commit/52d08318addbbcc565973d683d653e86d527f330#diff-b059a0d62ebcfc3546b9052f93b9e0d453d840b79db3784a89b7bdc3bd081e8dR583-R587) looks like it re-introduces path traversal.

**Comment by NotMyFault** [comment]
- https://github.com/CodeThreat/codethreat-jenkins-plugin/blob/628f1473ac2aa952870f105d5ff31d476217ef38/pom.xml#L99 is obsolete and can be removed. The BOM ships the credentials version to use.

**Comment by thyldrm** [comment]
Removed

**Comment by NotMyFault** [comment]
> hosting host

This command can be used by hosting team member only, not by users.
