### ISSUE TITLE
Please remove user tracking from default web UI

### ISSUE THREAD

**Issue by alithechemist** [jenkins-infra/repository-permissions-updater#3972]
### What feature do you want to see added?

I noticed that while running Jenkins on premises (debian package), the web UI tries to ping usage.jenkins.io.

It does not feel right and it should instead be something the users can opt in, and know  in advance.

Thank you in advance.

Chippy

**Comment by MarkEWaite** [comment]
Thanks for sharing your concern.  Unfortunately, this is not the correct location to report a concern with the usage reporting that has been part of Jenkins since at least 2010.

Please create an issue at https://issues.jenkins.io .  Before creating the issue, you may want to review a previous issue [JENKINS-40957](https://issues.jenkins.io/browse/JENKINS-40957) - More prominently offer option to opt out of anonymous usage statistics

**Comment by alithechemist** [comment]
Thanks!
